Feature/6 kanban board
Eyvgeniy/task-manager pull request #15
Opened 2021-05-13 11:28 UTC by Eyvgeniy

2021-05-13 19:09 UTC, greybutton requested changes
в итоге у тебя заработало?

2021-05-13 19:09 UTC, greybutton commented on app/javascript/packs/components/TaskBoard/index.js
> +import TaskBoard from './TaskBoard.jsx';
почему jsx?

2021-05-13 19:09 UTC, greybutton commented on Gemfile
> +gem 'webpacker-react', "~> 1.0.0.beta.1"
поставь последнюю не бету, 0.3.2 чтоли. может из за этого не работало

2021-05-13 19:09 UTC, greybutton commented on app/javascript/packs/application.js
> +import TaskBoard from './components/TaskBoard';
обрати внимание на путь где нужно было создать TaskBoard. У тебя лежит в `app/javascript/packs/components/TaskBoard/TaskBoard.jsx` в теории `app/javascript/components`

2021-05-13 19:34 UTC, Eyvgeniy commented on app/javascript/packs/components/TaskBoard/index.js
> +import TaskBoard from './TaskBoard.jsx';
Придерживаюсь соглашения, что файлы компонента или содержащие jsx, имеют расширение jsx. Если про расширения для файла в импорте, привычка с ноды. Так можно и убрать, но линтер не ругается.

2021-05-13 19:34 UTC, Eyvgeniy commented
> в итоге у тебя заработало?

Да, заработало

2021-05-13 19:35 UTC, Eyvgeniy commented on app/javascript/packs/application.js
> +import TaskBoard from './components/TaskBoard';
Пути поменял

2021-05-13 19:50 UTC, Eyvgeniy commented on Gemfile
> +gem 'webpacker-react', "~> 1.0.0.beta.1"
Поставил версию 0.3.2

2021-05-14 18:52 UTC, greybutton approved these changes

2021-05-14 18:52 UTC, greybutton commented on app/controllers/web/boards_controller.rb
> +    puts "CHECKING!!!!!!!!!!"
это можно убрать

2021-05-16 09:58 UTC, merged