Feature/7 tasks
Eyvgeniy/task-manager pull request #16
Opened 2021-05-17 14:25 UTC by Eyvgeniy

2021-05-17 14:28 UTC, Eyvgeniy commented on config/routes.rb
> +  namespace :api, defaults: { format: :json } do
Апи, который сделал js-routes запрашивает адреса без json формата, реилс на это ругается. Поэтому установил в роутах значение по умолчанию.
Можно было еще в таск контроллере прописать respond_to и написать ответ для html, но я подумал, это будет слишком многословно, так как пришлось бы для каждого метода прописывать.

2021-05-17 19:18 UTC, greybutton requested changes

2021-05-17 19:18 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import ColumnHeader from '../ColumnHeader';
попробуй вместо относительных путей `../` написать `components/Task`

2021-05-17 19:18 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import TasksRepository from '../../repositories/TasksRepository';
repositories/TasksRepository

2021-05-17 19:18 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import TaskForm from '../../forms/TaskForm';
forms/TaskForm

2021-05-17 19:18 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +      const taskState = data.items[0].state;
не понял почему так, в параметрах же есть state

2021-05-17 19:18 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +        console.log(data);
можно удалить

2021-05-17 19:18 UTC, greybutton commented on app/javascript/repositories/TasksRepository.js
> +import routes from '../routes';
routes

2021-05-17 19:18 UTC, greybutton commented on app/javascript/repositories/TasksRepository.js
> +import FetchHelper from '../../../utils/fetchHelper';
utils/fetchHelper

2021-05-17 19:18 UTC, greybutton commented on utils/fetchHelper.js
> +import axios from 'axios';
не там лежит, верно в app/javascript/utils/fetchHelper.js

2021-05-17 19:18 UTC, greybutton commented on utils/keysConverter.js
> +import humps from 'humps';
app/javascript/utils/keysConverter.js

2021-05-17 19:18 UTC, greybutton commented on config/routes.rb
> +  namespace :api, defaults: { format: :json } do
defaults: { format: :json } оставить, а respond_to добавить в ApplicationController для апи и тогда не нужно будет для всего прописывать respond_to

2021-05-18 12:04 UTC, Eyvgeniy commented on config/routes.rb
> +  namespace :api, defaults: { format: :json } do
Значит я правильно сделал

2021-05-18 12:04 UTC, Eyvgeniy commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import ColumnHeader from '../ColumnHeader';
Поменял

2021-05-18 12:04 UTC, Eyvgeniy commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import TasksRepository from '../../repositories/TasksRepository';
Поменял

2021-05-18 12:04 UTC, Eyvgeniy commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import TaskForm from '../../forms/TaskForm';
Поменял

2021-05-18 12:05 UTC, Eyvgeniy commented on app/javascript/components/TaskBoard/TaskBoard.js
> +      const taskState = data.items[0].state;
Убрал лишний код (task_state)

2021-05-18 12:05 UTC, Eyvgeniy commented on app/javascript/components/TaskBoard/TaskBoard.js
> +        console.log(data);
Удалил

2021-05-18 12:05 UTC, Eyvgeniy commented on app/javascript/repositories/TasksRepository.js
> +import routes from '../routes';
Исправил

2021-05-18 12:05 UTC, Eyvgeniy commented on app/javascript/repositories/TasksRepository.js
> +import FetchHelper from '../../../utils/fetchHelper';
Исправил

2021-05-18 12:05 UTC, Eyvgeniy commented on utils/fetchHelper.js
> +import axios from 'axios';
Исправил

2021-05-18 12:06 UTC, Eyvgeniy commented on utils/keysConverter.js
> +import humps from 'humps';
Исправил

2021-05-18 16:58 UTC, greybutton requested changes
как будто забыл запушить изменения) проверь плис, что запушил и во всех файлах мерджа пути типа `../` поправил

И еще у нас в обучалке в интерфейсе линк проверь плис, почему то отображается `https://github.com/https://github.com/Eyvgeniy/task-manager/pull/16Eyvgeniy/task-manager/pull/16`

2021-05-19 06:27 UTC, Eyvgeniy commented
ИСправм

> как будто забыл запушить изменения) проверь плис, что запушил и во всех файлах мерджа пути типа `../` поправил
> 
> И еще у нас в обучалке в интерфейсе линк проверь плис, почему то отображается `https://github.com/https://github.com/Eyvgeniy/task-manager/pull/16Eyvgeniy/task-manager/pull/16`

### Исправил

2021-05-19 06:42 UTC, greybutton approved these changes

2021-05-19 16:09 UTC, merged