Feature/7 assignee
Eyvgeniy/task-manager pull request #17
Opened 2021-05-21 07:56 UTC by Eyvgeniy

2021-05-24 07:29 UTC, greybutton requested changes
в коде не должно остаться task.id, task.state, task.author и т.п. (для юзера тоже) все через презентеры

2021-05-24 07:29 UTC, greybutton commented on app/javascript/components/Form/Form.js
> +        helperText={errors.author}
почему ошибки автора?

2021-05-24 07:29 UTC, greybutton commented on app/javascript/components/Form/Form.js
> +      {TaskPresenter.author(task) && (
у нас есть моды редактирования, лучше на них ориентироваться

2021-05-24 10:41 UTC, Eyvgeniy commented on app/javascript/components/Form/Form.js
> +        helperText={errors.author}
Исправил

2021-05-24 10:43 UTC, Eyvgeniy commented on app/javascript/components/Form/Form.js
> +      {TaskPresenter.author(task) && (
Исправил. Прокинул мод от TaskBoard к Form. Но разве это не будет более сложно?
Еще проверка mode === 'edit', мне нравится. Подумаю может ее как-то получше сделать ))

2021-05-24 14:26 UTC, Ensaphelon requested changes

2021-05-24 14:26 UTC, Ensaphelon commented on app/javascript/components/AddPopup/AddPopup.js
> +            onClick={handleCreate}
handleCreate - не понятно что создается

2021-05-24 14:26 UTC, Ensaphelon commented on app/javascript/components/EditPopup/EditPopup.js
> +  onDestroyCard,
onDestroyCard -> onCardDestroy

следуй правилу: `on{Object}{Action}` или `handle{Object}{Action}`

2021-05-24 14:26 UTC, Ensaphelon commented on app/javascript/components/EditPopup/EditPopup.js
> +  onDestroyCard,
Проверь это везде

2021-05-24 14:26 UTC, Ensaphelon commented on app/javascript/components/EditPopup/EditPopup.js
> +      alert(`Destruction Failed! Error: ${error.message}`);
Destruction лучше заменить на Deleting

2021-05-24 14:26 UTC, Ensaphelon commented on app/javascript/components/UserSelect/UserSelect.js
> +  const [isFocused, setFocus] = useState(false);
Зачем нам это?

2021-05-24 14:26 UTC, Ensaphelon commented on app/javascript/components/UserSelect/UserSelect.js
> +            styles={{ menuPortal: (base) => ({ ...base, zIndex: 9999 }) }}
че то выглядит как костылек с zIndex

2021-05-24 14:48 UTC, Eyvgeniy commented on app/javascript/components/AddPopup/AddPopup.js
> +            onClick={handleCreate}
Исправил

2021-05-24 14:48 UTC, Eyvgeniy commented on app/javascript/components/EditPopup/EditPopup.js
> +  onDestroyCard,
Исправил

2021-05-24 14:49 UTC, Eyvgeniy commented on app/javascript/components/EditPopup/EditPopup.js
> +      alert(`Destruction Failed! Error: ${error.message}`);
Исправил

2021-05-24 15:14 UTC, Eyvgeniy commented on app/javascript/components/UserSelect/UserSelect.js
> +            styles={{ menuPortal: (base) => ({ ...base, zIndex: 9999 }) }}
Такой код предлагает использовать сама библиотека https://react-select.com/advanced#portaling

2021-05-24 15:27 UTC, Eyvgeniy commented on app/javascript/components/UserSelect/UserSelect.js
> +  const [isFocused, setFocus] = useState(false);
Убрал

2021-05-27 14:03 UTC, Ensaphelon commented on app/javascript/components/UserSelect/UserSelect.js
> +            styles={{ menuPortal: (base) => ({ ...base, zIndex: 9999 }) }}
а вот если 9998 вставить то будет работать?)

2021-05-27 14:04 UTC, Ensaphelon commented on app/javascript/components/UserSelect/UserSelect.js
> +            styles={{ menuPortal: (base) => ({ ...base, zIndex: 9999 }) }}
А если не UserSelect а будет другая сущность то тоже 9999 туда вставлять будем?)

2021-05-27 20:36 UTC, Eyvgeniy commented on app/javascript/components/UserSelect/UserSelect.js
> +            styles={{ menuPortal: (base) => ({ ...base, zIndex: 9999 }) }}
UserSelect располагается в модалке, у нее z-index 1300. Меню со значениями находиться за пределами модалки.
Поэтому используем портал, чтобы навесить ему z-index. Можно объявить переменную с этим значением и использовать ее.

2021-05-31 13:19 UTC, Ensaphelon approved these changes

2021-05-31 13:50 UTC, merged